on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout the repository
        uses: actions/checkout@v3
      - name: ðŸ“¦ Create zip file for Universal Notifier
        run: |
          cd "${{ github.workspace }}"
          zip -r universal_notifier.zip *
      - name: ðŸ“¤ Upload the zip file as a release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "${{ github.workspace }}/universal_notifier.zip"
          asset_name: universal_notifier.zip
          tag: ${{ github.ref }}
          overwrite: true
